### ISSUE TITLE
Translation helpers

### ISSUE THREAD

**Issue by justinwoo** [justinwoo/advent-of-justin-2018#1]
It would be fun to have people help translate these posts, so I'll make this tally to keep track of which articles will be translated by who, and in what language.

To claim an article, please comment on this issue with the article you'd like to translate and in what language you will translate it to. Then make a PR for the article with your translation prepended. Thanks!

- [x] 01 Simple-JSON, German by @alech, Spanish by @mvaldesdeleon
- [ ] 02 Psc-Package
- [ ] 03 Tanghulu
- [ ] 04 Easy PureScript nix
- [x] 05 Type classes are pattern matching for types, Finnish by @miikka, German by @BenBals
- [x] 06 Home Run Ball, German by @BenBals
- [ ] 07 Spacchetti
- [ ] 08 Type level path params
- [ ] 09 Psc-Package2Nix
- [ ] 10 Oh-Yes, datatype generic based
- [x] 11 Inferred record types with Simple-JSON, Japanese by @noolbar
- [ ] 12 Tortellini
- [ ] 13 Type annotated type level string templates
- [ ] 14 Implementing your own compiler type class
- [ ] 15 Bower to nix
- [ ] 16 Dynamically typed errors in purescript
- [ ] 17 Union Constraints
- [ ] 18 Jajanmen
- [x] 19 FFI in purescript, Spanish by @mvaldesdeleon, Japanese by @entyo 
- [ ] 20 Pandoc with Nix
- [ ] 21 Instance chains and Kazunoko
- [ ] 22 Naporitan
- [ ] 23 Inferred Error Types
- [x] 24 Modeling Chart.js spec building with rows, Japanese by @noolbar

**Comment by miikka** [comment]
I can translate e.g. number 5 into Finnish.

**Comment by alech** [comment]
Will start with translating 01 into German.

**Comment by BenBals** [comment]
I'd like to contribute a German version of No. 5 and 6.

**Comment by mvaldesdeleon** [comment]
I'll do Spanish for No 1 and No 19.

**Comment by noolbar** [comment]
is it too late to contribute? I make the Japanese translation of No1, No11 and No24.

**Comment by justinwoo** [comment]
@noolbar please do! I'll update the original entries accordingly

**Comment by justinwoo** [comment]
The advent of over now. Thanks for contributing, everyone!
